src/java/model/Cart.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.DAO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author trant
 */
public final class Cart {

    private List<Item> items;

    public Cart() {
        items = new ArrayList<>();
    }

    public Cart(List<Item> items) {
        this.items = items;
    }

    public List<Item> getItems() {
        return items;
    }

    public void setItems(List<Item> items) {
        this.items = items;
    }

    public int getQuantityById(int id) {
        Item i = getItemById(id);
        return i.getQuantity();
    }

    private Item getItemById(int id) {
        for (Item i : items) {
            if (i.getProduct().getId() == id) {
                return i;
            }

        }
        return null;
    }

public void addItem(Item item) {
    Item it;
    
        if (getItemById(item.getProduct().getId()) != null) {
            it = getItemById(item.getProduct().getId());
            
                 it.setQuantity(it.getQuantity() + item.getQuantity());
            
           
        } else {
            items.add(item);
        }
    
}


    public void deleteItemByItem(Item item) {
        Item it;
        it = getItemById(item.getProduct().getId());
        items.remove(it);
    }

    public void removeItemById(int id) {

        Item item = getItemById(id);
        if (item != null) {
            items.remove(item);

        }

    }

    public double getTotalMoney() {
        double total = 0;
        for (Item item : items) {
            total += item.getQuantity() * (item.getPrice());
        }
        return total;
    }

    public Product getProductById(int id, List<Product> list) {
        for (Product product : list) {
            if (product.getId() == id) {
                return product;
            }
        }
        return null;
    }

    //
    public  Cart(String txt, List<Product> list) {
        items = new ArrayList<>();
        try {
            if (txt != null && txt.length() != 0) {
                String[] str = txt.split("/");
                for (String s : str) {
                    String[] n = s.split(":");
                    int id = Integer.parseInt(n[0]);
                    int quantity=Integer.parseInt(n[1]);
                    DAO d= new DAO();
   
                    Product p =d.getProductById(id);
                    Item t=new Item(p,quantity,p.getPrice());
                    addItem(t);
                }
            }
        } catch (NumberFormatException e) {
        }
    }

}

src/java/model/Product.java
package model;

import java.util.Date;

public class Product {
    private int id;
    private String name;
    private int quantity;
    private double price;
    private Date releaseDate;
    private String describe;
    private String image;
    private Category category;

    // Constructors
    public Product() {
    }

    public Product(int id, String name, int quantity, double price, Date releaseDate, String describe, String image, Category category) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.releaseDate = releaseDate;
        this.describe = describe;
        this.image = image;
        this.category = category;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Category getCid() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }
}

src/java/controller/ShopServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import com.sun.corba.se.spi.orb.OperationFactory;
import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.List;
import model.Cart;
import model.Item;
import model.Product;

/**
 *
 * @author trant
 */
@WebServlet(name = "ShopServlet", urlPatterns = {"/shop"})
public class ShopServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ShopServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ShopServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        processRequest(request, response);
        DAO d = new DAO();
        List<Product> list ;
        list = d.getALL();
        Cookie[] arr = request.getCookies();
        String txt = "";
        if (arr != null) {
            for (Cookie cookie : arr) {
                if (cookie.getName().equals("cart")) {
                    txt += cookie.getValue();
                }
            }
        }
        Cart cart = new Cart(txt, list);
        List<Item> listItem = cart.getItems();
        int n;
        if (listItem != null) {
            n = listItem.size();
        } else {
            n = 0;
        }
      
        HttpSession ss= request.getSession();
        ss.setAttribute("size", n);
        request.setAttribute("data", listItem);
        request.getRequestDispatcher("list").forward(request, response);
        

    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/controller/accountServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.Customer;
import model.CustomerDetail;

/**
 *
 * @author trant
 */
@WebServlet(name = "accountServlet", urlPatterns = {"/account"})
public class accountServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet accountServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet accountServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        processRequest(request, response);
//day la username
        String name = (String) request.getParameter("name");
        DAO d = new DAO();
        Customer c1 = d.getCustomerByUserName(name);
        CustomerDetail c2 = d.getCustomerDetailById(c1.getId());
        request.setAttribute("nameholder", c1.getName());
        request.setAttribute("id", c1.getId());

        request.setAttribute("passwordholder", c1.getPassword());
        request.setAttribute("emailholder", c2.getEmailAddress());
        request.setAttribute("phoneholder", c2.getPhoneNumber());
        request.setAttribute("countryholder", c2.getCountry());
        request.getRequestDispatcher("account.jsp").forward(request, response);

    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

    public static void main(String[] args) {
        DAO d = new DAO();
       CustomerDetail c= d.getCustomerDetailById(1095);
        System.out.println(c.getEmailAddress());

    }
}

src/java/controller/homeServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.List;
import java.util.Random;
import model.Customer;
import model.Product;

/**
 *
 * @author trant
 */
@WebServlet(name="homeServlet", urlPatterns={"/home"})
public class homeServlet extends HttpServlet {
   
    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet homeServlet</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet homeServlet at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        
        
          DAO d = new DAO();
     
        Random random = new Random();
        int randomNumber = random.nextInt(4) + 1;
        String input = "";
        switch (randomNumber) {
            case 1:
                input += "IPHONE";
                break;
            case 2:
                input += "SAMSUNG";
                break;
            case 3:
                input += "OPPO";
                break;
            case 4:
                input += "VSMART";
                break;
            default:
                break;
        }
        List<Product> products = d.RandomProduct(input);

        
            HttpSession session = request.getSession();
            
            request.setAttribute("product", products);
         

          
        
       ///
        if (session.getAttribute("account")!=null) {
            request.getRequestDispatcher("homeLogged.jsp").forward(request, response);
        }
        else{
        request.getRequestDispatcher("home.jsp").forward(request, response);
    } 
    }

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        processRequest(request, response);
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/OrderHistory.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%-- 
    Document   : OrderHistory
    Created on : Jul 19, 2023, 6:53:51 PM
    Author     : trant
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html>
    <head>
        <title>Order History</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }

            h1 {
                text-align: center;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            th, td {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }

            th {
                background-color: #f2f2f2;
            }

            tr:nth-child(even) {
                background-color: #f2f2f2;
            }

        </style>

    </head>
    <body>
          <a href="dash.jsp">Go back to homepage</a>
        <h1>Order History</h1>
        <table id="order-table">
            <tr>
                <th>Order ID</th>
                <th>Customer ID</th>
                <th>Date</th>
                <th>Total Money</th>
            </tr>
            <c:forEach var="o" items="${requestScope.order}">
                <tr>
                    <td>${o.id}</td>
                    <td>${o.cid}</td>
                    <td>${o.date}</td>
                    <td> <fmt:formatNumber pattern="#,##0VND" value="${o.totalMoney}"></fmt:formatNumber>
                        <a style="float:right" href="showorderline?oid=${o.id}">Detail</a>
                        </td>
                    </tr>
            </c:forEach>

        </table>
        <script src="script.js"></script>
    </body>
</html>

web/Orderline.jsp
<%-- 
    Document   : OrderHistory
    Created on : Jul 19, 2023, 6:53:51 PM
    Author     : trant
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>


<!DOCTYPE html>
<html>
    <head>
        <title>Order History</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }

            h1 {
                text-align: center;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            th, td {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }

            th {
                background-color: #f2f2f2;
            }

            tr:nth-child(even) {
                background-color: #f2f2f2;
            }

        </style>

    </head>
    <body>

        <a href="showOrder">Go back to Order</a>
        <h1>Order History</h1>
        <table id="order-table">
            <tr>
                <th>Order ID</th>
                <th>Product ID</th>
                <th>Quantity</th>
                <th>Price</th>
            </tr>


            <c:forEach var="o" items="${requestScope.orderline}">
                <tr>
                    <td>${o.oid}</td>
                    <td>${o.pid}  <a href="productview?id=${o.pid}">view</a></td>
                    <td>${o.quantity}</td>
                    <td> <fmt:formatNumber pattern="#,##0VND" value="${o.price}"></fmt:formatNumber> </td>



                    </tr>
            </c:forEach>

        </table>


        <script src="script.js"></script>
    </body>
</html>

web/login.jsp
<%-- 
    Document   : login
    Created on : Jul 6, 2023, 3:15:56 AM
    Author     : trant
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>
<html lang="en">
  <head>
  	<title>Login 10</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="css/style.css">

	</head>
	<body class="img js-fullheight" style="background-image: url(images/bg.jpg);">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Hello There!!</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center">Login to Boutique</h3>
                        <h3 style="color: red" class="mb-4 text-center">${requestScope.error}</h3>
                                                <h3 style="color: red" class="mb-4 text-center">${requestScope.deny}</h3>

                        <form action="login" method="post" class="signin-form">
		      		<div class="form-group">
                                     <c:set var="cookie" value="${pageContext.request.cookies}"  />
                                     <input name="username"  type="text" class="form-control" placeholder="Username" value="${cookie.usernameC.value}" required>
		      		</div>
	            <div class="form-group">
                        <input id="password-field" type="password" name="password" class="form-control" placeholder="Password" value="${cookie.passwordC.value}" required>
	              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
		            	<label class="checkbox-wrap checkbox-primary"  >Remember Me
                                    <input name="remember" value="ON" type="checkbox"  checked >
									  <span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="SignUp.jsp" style="color: #fff">Register new Account</a>
								</div>
	            </div>
	          </form>
	       
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="js/jquery.min.js"></script>
  <script src="js/popper.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/main.js"></script>

	</body>
</html>

web/mailSender.jsp
<%-- 
    Document   : mailSender
    Created on : Jul 12, 2023, 12:28:02 AM
    Author     : trant
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>GeeksforGeeks</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <form action="Email" method="post">
            <div align="center"> <h1>Enter the Credentials: </h1>
            <input type="hidden" name="action" value="add">
            
            <label for="sID">Sender ID :</label> <br>
            <input id="sID" type="text" name="id"> <br>
             
            <label for="sMail">Sender Email :</label> <br>
            <input id="sMail" type="email" name="emailSender"> <br>
            
            <label for="pw">Password :</label> <br>
            <input id="pw" type="password" name="password"> <br>
            
            <label for="rMail">Receiver Email :</label> <br>
            <input id="rMail" type="email" name="emailReceiver"> <br>
             
            <label for="sub">Subject :</label> <br>
            <input id="sub" type="text" name="subject"> <br>
             
            <label for="message">Message :</label> <br>
            <input id="message" type="text" name="message"><br>
            <input type="submit" value="Send">
             
            </div>
        </form>
    </body>
</html>

web/setrole.jsp
<%-- 
    Document   : setrole
    Created on : Jul 21, 2023, 8:52:53 AM
    Author     : trant
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body style="text-align: center">
        <form action="setRole" method="post"> 
            Customer ID:  <input type="text" name="id" value="${requestScope.id}" /><br>
            Role:  <input type="text" name="role" value="${requestScope.role}" /><br>
            <input type="submit" value="submit"/>
        </form>
    </body>
</html>